### ISSUE TITLE
implement correct updateSession in FacebookConnector

### ISSUE THREAD

**Issue by chentsulin** [bottenderjs/bottender-facebook#59]
now it throws:

Warning: getUserProfile() failed, `session.user` will only have `id`
TypeError: Cannot read property 'getUserProfile' of undefined
    at FacebookConnector.updateSession (/Users/chentsulin/Projects/yoctol/bottender-facebook/node_modules/bottender/lib/bot/MessengerConnector.js:178:35)
    at /Users/chentsulin/Projects/yoctol/bottender-facebook/examples/facebook-batch/node_modules/bottender/lib/bot/Bot.js:137:31
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by chentsulin** [comment]
In Bottender v1, now we skip profile by default, so it's not a problem not anymore.
